### ISSUE TITLE
hi,can you add trained model weights?

### ISSUE THREAD

**Issue by taner45** [AymenBOUGUERRA/Unet-denoising-tool-for-textbook-images#1]

**Comment by AymenBOUGUERRA** [comment]
Hello Tanner45,
I have provided the link to download a pre-trained model, all you need to do is to put it in the the same directory of the code to be loaded
the link to download the pre-trained model 
https://drive.google.com/file/d/1wH6Ioqkk6zXxVgOFbCcYYVeatReZOVEs/view?usp=sharing (137 Mo)

**Comment by taner45** [comment]
Hello AymenBOUGUER,
when I try download with  "!wget https://drive.google.com/file/d/1wH6Ioqkk6zXxVgOFbCcYYVeatReZOVEs/view?usp=sharing " 
I get error unable to open file (file signature not found)..


thanks in advance.

**Comment by AymenBOUGUERRA** [comment]
Hello, since the file is larger than 100 Mo, google drive can't intiate its anti-virus check, and thus wont generate a signature, the error you are receiving is a translation of this :
![image](https://user-images.githubusercontent.com/97101162/199045397-1ba4577c-5214-417c-8a3b-d8d95cc9264b.png)

There is a solaution in this guide on how to download google cloud files with the same problem 

https://bcrf.biochem.wisc.edu/2021/02/05/download-google-drive-files-using-wget/

**Comment by taner45** [comment]
Thanks Aymen,
but my company gives permission only github. because of that I said can you load your repostory. Ok ı can handle it my home computer.
thank you...

**Comment by AymenBOUGUERRA** [comment]
Hello Taner45,
I have updated the code to be more user friendly, I originally made that code out of necessity for another project, and I didn't  write it in a way to be more generally used, the code now works better (as it was wrote on google col-lab hens the im_show error) and is now should be easier to use, all what is needed now is to run the script while the model and the image are on the same dir and voila.. 
I will also be posting next week a 800Mo .exe file that would have all the libraries and the model built-in and would work just by typing the image name and path (as you can see in the read-me part)
I hope this tool was useful for you and if I am open to feedback in case you couldn't run it or anything else.

**Comment by taner45** [comment]
Hello AymenBOUGUER,
I couldn't load your model weights because ı am taking  ValueError: bad marshal data (unknown type code). ı think this python version difference........
I will be wait your new libraries.
thank you.

**Comment by AymenBOUGUERRA** [comment]
Hello Taner45 an sorry for the late response,
I did upload an .exe file that should work without issues regarding conflicts and version diffrances

Check the updated description of the project and you will find the link there (about 800Mo)
then just make sure to put the image in the same dir and type its name (with the .png)  or type the full path (again with the .png)
Good luck
